export const siteConfig = {
  name: "Ahmed Raza",
  title: "Ahmed Raza Portfolio – Web Design, Development & Creative Solutions",
  description:
    "Explore Ahmed Raza's portfolio showcasing innovative web design, development expertise, and creative digital solutions. Expert in React, Next.js, TypeScript, and modern web technologies. Discover personalized and professional work that delivers results.",
  url: "https://dev-ar-portfolio.vercel.app",
  ogImage: "/og-image.png",
  twitterHandle: "@AhmedRazaa956",
  author: "Ahmed Raza",
  keywords: [
    "Ahmed Raza",
    "Web Developer",
    "Frontend Developer",
    "React Developer",
    "Next.js Developer",
    "TypeScript Developer",
    "Web Designer",
    "Portfolio",
    "Full Stack Developer",
    "UI/UX Designer",
    "JavaScript Developer",
    "Modern Web Development",
    "Creative Solutions",
    "Digital Solutions",
    "Website Development",
    "Web Design Services",
    "Frontend Engineering",
    "React.js",
    "Next.js Framework",
    "TypeScript Development",
    "Responsive Web Design",
    "User Experience Design",
    "Web Application Development",
  ],
  locale: "en_US",
  type: "website",
  // Contact Information
  contact: {
    email: "leadzahmed@gmail.com",
    phone: "+923187380601",
    github: "https://github.com/Ahmed-Crystallite",
    linkedin: "https://pk.linkedin.com/in/ahmed-raza-96027a250",
    whatsapp: "https://wa.me/923187380601",
  },
};

export const defaultMetadata = {
  metadataBase: new URL(siteConfig.url),
  title: {
    default: siteConfig.title,
    template: `%s | ${siteConfig.name}`,
  },
  description: siteConfig.description,
  keywords: siteConfig.keywords,
  authors: [{ name: siteConfig.author }],
  creator: siteConfig.author,
  publisher: siteConfig.author,
  formatDetection: {
    email: false,
    address: false,
    telephone: false,
  },
  openGraph: {
    type: siteConfig.type,
    locale: siteConfig.locale,
    url: siteConfig.url,
    title: siteConfig.title,
    description: siteConfig.description,
    siteName: siteConfig.name,
    images: [
      {
        url: siteConfig.ogImage,
        width: 1200,
        height: 630,
        alt: siteConfig.title,
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    title: siteConfig.title,
    description: siteConfig.description,
    images: [siteConfig.ogImage],
    creator: siteConfig.twitterHandle,
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-video-preview": -1,
      "max-image-preview": "large" as const,
      "max-snippet": -1,
    },
  },
  icons: {
    icon: "/favicon.ico",
    shortcut: "/favicon.ico",
    apple: "/apple-touch-icon.png",
  },
  manifest: "/site.webmanifest",
  alternates: {
    canonical: siteConfig.url,
  },
  verification: {
    google: process.env.NEXT_PUBLIC_GOOGLE_SITE_VERIFICATION || "",
    // yandex: process.env.NEXT_PUBLIC_YANDEX_VERIFICATION || "",
    // bing: process.env.NEXT_PUBLIC_BING_VERIFICATION || "",
  },
};
