import { NextResponse } from "next/server";
import nodemailer from "nodemailer";

export async function POST(request) {
    try {
        const { name, email, phone, services, message, pageURL } = await request.json();
        const transporter = nodemailer.createTransport({
            service: "gmail",
            host: "ahmedrza14@gmail",
            port: 587,
            secure: true,
        });
        const mailOptions = {
            from: 'ahmedrza14@gmail',
            to: 'ahmedrza14@gmail',
            subject: `New Lead Generated By Creative Logo Designs`,
            html: `<div style="width:100%;height:100%;padding:1rem;background-color: #efefef;">
                <div style="display:flex; align-items: center;">
                    <h4>Name : ${name}</h4>
                </div>
                <div style="display:flex; align-items: center;">
                    <h4>Email : ${email}</h4>
                </div>
                <div style="display:flex; align-items: center;">
                    <h4>Phone : ${phone}</h4>
                </div>
                <div style="display:flex; align-items: center;">
                    <h4>Services : ${services}</h4>
                </div>
                <div style="display:flex; align-items: center;">
                    <h4>Message : ${message}</h4>
                </div>
                <div style="display:flex; align-items: center;">
                    <h4>From : ${pageURL}</h4>
                </div>
            </div>`
        };
        await transporter.sendMail(mailOptions);
        return NextResponse.json({ "mesaage": "Email sent successfully", "status": 200 });
    } catch (error) {
        return NextResponse.json({ "mesaage": "Failed to sent Email", "status": 500 });
    }
}
// let nodemailer = require('nodemailer');

// let transporter = nodemailer.createTransport({
//     service: 'gmail',
//     auth: {
//         user: 'leadzahmed@gmail.com',
//         pass: 'yourpassword'
//     }
// });

// let mailOptions = {
//     from: 'leadzahmed@gmail.com',
//     to: 'leadzahmed@gmail.com',
//     subject: 'Sending Email using Node.js',
//     text: 'Lead'
// };

// transporter.sendMail(mailOptions, function (error, info) {
//     if (error) {
//         console.log(error);
//     } else {
//         console.log('Email sent: ' + info.response);
//     }
// });