import "./globals.css";

import { primary, secondary } from "../configs/font";
import Header from "@/components/Header/header";
import Footer from "@/components/Footer/Footer";
export const metadata = {
  title: "Ahmed Raza Portfolio",
  description: "Generated by create next app",
};
// Export RootLayout
const RootLayout = ({ children }) => {
  return (
    <html lang="en">
      <head>
      <link rel="icon" href="/favicon.ico" />
        <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png" />
      </head>
      <body className={`${primary.variable} ${secondary.variable}`}>
        <Header/>
        {children}
        <Footer/>
      </body>
    </html>
  );
};

export default RootLayout;