import "./globals.css";

import { primary, secondary } from "../configs/font";
export const metadata = {
  title: "Ahmed Raza Portfolio",
  description: "Generated by create next app",
};
// Export RootLayout
const RootLayout = ({ children }) => {
  return (
    <html lang="en">
      <body className={`${primary.variable} ${secondary.variable}`}>
        <main>{children}</main>
      </body>
    </html>
  );
};

export default RootLayout;